name: Format
on:
  push:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: npm install
      - name: Run Prettier
      - run: npx prettier --write **/*.js
