name: Prettier

on:
  pull_request:
    paths:
      - '**/*.{js,jsx,ts,tsx,json,css,scss,md}'  # Adjust file extensions as needed

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write .
