name: Prettier
on:
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Add Execution Permissions
        run: 'chmod +x ./node_modules/.bin/prettier'

      - name: Run Prettier
        run: 'npx prettier --write "**/*.js"'
