name: Prettier
on:
  push:
    branches: [prettier-test]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: 'npx prettier --write "**/*.js"'
